---
title: "socialNavigationAnalysis"
author: "Neel"
date: "2026-05-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/mcpro/OneDrive/Documents/WAVE LAB/Code/socialNavigation/tools")

library(tidyverse)
library(paletteer)
```

```{r}
all_data <- read.csv("data/dataframe_answer.csv", header=TRUE)

#delete all test data

all_data <- all_data |>
  filter(participant_id != "{{%PROLIFIC_PID%}}") |>
  filter(!str_detect(participant_id, "no_query_worker"))

length(unique(all_data$participant_id))

uniq <- unique(all_data$participant_id)
uniq

```


```{r}


short_data <- all_data |>
  select(participant_id, response, response_time, accuracy, trial_rotation, stripe_angle_top, stripe_angle_bottom, background_group, identical)

short_data <- short_data |>
  mutate(group = case_when(
    background_group %in% c("3_5", "5_3") ~ "different",
    background_group %in% c("3_3", "5_5") ~ "same"
  ))

short_data$group = as.factor(short_data$group)





short_data <- short_data |>
  filter(abs(response_time - mean(response_time)) <= (2 * sd(response_time))) #first filter out those participants outside of 2sds from the mean



short_data <- short_data |>
  group_by(participant_id) |>
  filter(abs(response_time - mean(response_time)) <= (2 * sd(response_time))) |> #then do the same, but at the individual level of the data
  ungroup()


nrow(all_data) - nrow(short_data) #num rows removed
```

```{r}
#SKIP
plot(short_data$group, short_data$response_time, labs(main = "Reaction Time by Background", xlab = "Condition", ylab = "Response Time, ms"))
```


```{r}
#SKIP
short_data <- short_data |>
  mutate(log_response_time = log(response_time))

plot(short_data$group, short_data$log_response_time)




```


```{r}
#SKIP
bar_data <- short_data |>
  group_by(group) |>
  summarize(
    mean = mean(log_response_time),
    sd = sd(log_response_time),
    n = n(),
    se = sd/sqrt(n)
  )


ggplot(bar_data, aes(x=group, y=mean, fill=group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se))


```



```{r}
bar_data_2 <- short_data |>
  group_by(background_group) |>
  summarize(
    mean = mean(log_response_time),
    sd = sd(log_response_time),
    n = n(),
    se = sd/sqrt(n)
  )


ggplot(bar_data_2, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se))


```




```{r}
#SKIP
participant_means <- short_data |>
  group_by(group, participant_id ) |>
  summarize(avg_log_rt = mean(log_response_time))


t.test(avg_log_rt ~ group, data = participant_means)

```


```{r}
real_bar_data <- short_data |>
  filter(accuracy == 1) |>
  group_by(background_group) |>
  summarize(
    mean = mean(response_time),
    sd = sd(response_time),
    n = n(),
    se = sd/sqrt(n)
  )


ggplot(real_bar_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) + 
  labs(title = "Task Reaction Times", x = "Condition", y = "Reaction time, ms")

```
```{r}

grouped_data <- short_data |>
  filter(accuracy == 1) |>
  group_by(participant_id, background_group) |>
  summarize(mean_rt = mean(response_time), mean_acc = mean(accuracy), total_trials = n()) |>
  ungroup()


grouped_data$background_group = as.factor(grouped_data$background_group)

diff_groups_anova <- aov(mean_rt ~ background_group + Error(participant_id/background_group), data=grouped_data)

summary(diff_groups_anova)

library(emmeans)
post_hoc <- emmeans(diff_groups_anova, ~background_group)

pairs(post_hoc, adjust = "tukey")

```
```{r}
library(afex)

rm_anova <- aov_ez(id = "participant_id", 
                   dv = "mean_rt", 
                   data = grouped_data, 
                   within = "background_group")

summary(rm_anova)

```

```{r}
acc_data <- all_data |>
  group_by(background_group) |>
  summarize(
    mean = mean(accuracy),
    sd = sd(accuracy),
    n = n(),
    se = sd/sqrt(n)
  )





ggplot(acc_data, aes(x=background_group, y=mean, fill=background_group)) +
  geom_col() +
  geom_errorbar(aes(ymin= mean - se, ymax = mean + se)) +
  labs(title = "Stripe Angle Match Accuracy", x="Condition", y= "Accuracy")


grouped_data_acc <- all_data |>
  group_by(participant_id, background_group) |>
  summarize(mean_rt = mean(response_time), mean_acc = mean(accuracy)) |>
  ungroup()


grouped_data_acc$background_group = as.factor(grouped_data_acc$background_group)




acc_anova <- aov_ez(id = "participant_id", 
                   dv = "mean_acc", 
                   data = grouped_data_acc, 
                   within = "background_group")

summary(acc_anova)

library(emmeans)

acc_hoc <- emmeans(acc_anova, ~background_group)

pairs(acc_hoc, adjust = "tukey")



```

```{r}
short_data$trial_rotation = as.factor(short_data$trial_rotation)

short_data |>
  group_by(trial_rotation) |>
  summarize(count = n())

```



